Add QR code from qrcode npm package
lumberhackers/ui-playground pull request #1
Opened 2022-10-17 21:33 UTC by ssomalraju2

2022-10-17 21:46 UTC, scvnc requested changes

2022-10-17 21:46 UTC, scvnc commented on tsconfig.json
> +, "src/scanQRCode.js", "src/scanQRCode.js"  ],
Lets turn scanQRCode into a typescript file so that we don't have to define it in this file :)

2022-10-17 21:46 UTC, scvnc commented on index.html
> +    <script type="application/javascript" src="scanQRCode.js"></script>
you should be able to remove this script tag.  The vue file will be able to reference

2022-10-17 21:46 UTC, scvnc commented on src/scanQRCode.ts
> +QRCode.toCanvas(canvas, 'sample text', function (error: any) {
we need to figure out a way to make this execute only when we know the <canvas> is on the DOM.

2022-10-17 22:22 UTC, scvnc commented on yarn.lock
> +  "resolved" "https://pkgs.dev.azure.com/osh-inc/_packaging/osh-inc/npm/registry/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz"
we also need to remove this because this is an internal npm feed.

2022-10-17 22:22 UTC, scvnc commented on yarn.lock
> +  "resolved" "https://pkgs.dev.azure.com/osh-inc/_packaging/osh-inc/npm/registry/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz"
I will pair with you on this tomorrow

2022-10-18 15:02 UTC, geppettodivacin commented on tsconfig.json
> +, "src/scanQRCode.js", "src/scanQRCode.js"  ],
This can be removed now, right?

2022-10-18 22:23 UTC, scvnc approved these changes

2022-10-18 22:30 UTC, merged